# Generated by Django 3.2.18 on 2023-04-21 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0003_meals_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('number_of_people', models.CharField(choices=[('one', '1 Person'), ('two', '2 People'), ('three', '3 People'), ('four', '4 People'), ('five_plus', '5+ People')], default='one', max_length=10)),
                ('Date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
