# Generated by Django 3.2.18 on 2023-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('section_title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('number_a', models.IntegerField()),
                ('title_a_small', models.CharField(max_length=30)),
                ('title_a_big', models.CharField(max_length=30)),
                ('number_b', models.IntegerField()),
                ('title_b_small', models.CharField(max_length=30)),
                ('title_b_big', models.CharField(max_length=30)),
                ('image_left_up', models.ImageField(upload_to='img/aboutus/')),
                ('image_Left_down', models.ImageField(upload_to='img/aboutus/')),
                ('image_right_up', models.ImageField(upload_to='img/aboutus/')),
                ('image_right_down', models.ImageField(upload_to='img/aboutus/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='img/team/')),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('instagram', models.TextField()),
            ],
            options={
                'verbose_name': 'Team Members',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
