# Generated by Django 3.2.18 on 2023-04-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0005_aboutus_teammembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image_Left_down',
            new_name='image_left_down',
        ),
    ]
