# Generated by Django 3.2.18 on 2023-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0006_rename_image_left_down_aboutus_image_left_down'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Service Cards',
                'verbose_name_plural': 'Service Cards',
            },
        ),
    ]
