# Generated by Django 3.2.18 on 2023-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0007_servicecards'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='img/hero/')),
                ('cta_text', models.TextField()),
                ('cta_link', models.TextField()),
            ],
            options={
                'verbose_name': 'Hero Container',
                'verbose_name_plural': 'Hero Container',
            },
        ),
    ]
