# Generated by Django 3.2.18 on 2023-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0008_herocontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontainer',
            name='cta_link',
        ),
    ]
