# Generated by Django 3.2.18 on 2023-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0009_remove_herocontainer_cta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontainer',
            name='title',
            field=models.TextField(),
        ),
    ]
