# Generated by Django 3.2.18 on 2023-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0012_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breakfast', models.TextField()),
                ('breakfast_weekend', models.TextField(null=True)),
                ('lunch', models.TextField()),
                ('lunch_weekend', models.TextField(null=True)),
                ('dinner', models.TextField()),
                ('dinner_weekend', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Dining Times',
                'verbose_name_plural': 'Dining Times',
            },
        ),
    ]
