# Generated by Django 3.2.18 on 2023-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0013_diningtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtimes',
            name='breakfast_weekend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diningtimes',
            name='dinner_weekend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diningtimes',
            name='lunch_weekend',
            field=models.TextField(blank=True, null=True),
        ),
    ]
